### ISSUE TITLE
Application damaged or incomplete

### ISSUE THREAD

**Issue by herrbischoff** [Sh1d0w/clean-links#6] opened 2020-07-01 11:21 UTC
### Environment

```
# sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101
```

```
Safari Version 13.1.1 (15609.2.9.1.2)
```

### Issue

After extraction of https://github.com/Sh1d0w/clean-links/releases/download/v1.2%2B10/Clean.Links.app.zip, Finder shows the application as unable to run. When trying to open it, the OS indeed rejects the application.

<img width="420" alt="Screenshot 2020-07-01 at 13 12 04" src="https://user-images.githubusercontent.com/8957346/86238355-a58d9380-bb9d-11ea-93cb-eb9847b4b2dd.png">

Checking the code out and building it on my machine works as expected. So there's probably just something wrong with the archive.

**Comment by Sh1d0w** [comment] 2020-07-01 13:43
That's really odd. I've just download and installed it from the link with no errors. Maybe the program you are using to extract the archive corrupts it or the zip was not fully downloaded when you attempted to open it? Anyways I am closing this as I can't reproduce it.

**Closed by Sh1d0w** 2020-07-01 13:43 UTC

**Comment by herrbischoff** [comment] 2020-07-01 14:14
Wow, that's indeed the case. Never though twice about it because I've never encountered this before. The Unarchiver apparently does something weird to the file. As soon as I use the internal Archive Utility, the file is complete and correct. Sorry for not checking this before opening an issue.
